version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      TZ: Etc/GMT+6 # America/Costa_Rica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # volumes:
    #   - ~/Documents/docker/postgres-data:/var/lib/postgresql/data
# docker-compose up -d
# docker-compose down

# In case you are in a swarm mode type this to leave
# docker swarm leave
